In [1]:
import tensorflow as tf

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## 矢量加法

In [5]:
with tf.Graph().as_default():
    #创建包含六个元素的一位维张量
    primes = tf.constant([2,3,5,7,11,13],dtype=tf.int32)
    #创建初始化为1的张量
    ones = tf.ones([6],dtype=tf.int32)
    #+
    just_bryond_primes = tf.add(primes,ones)
    
    #会话
    with tf.Session() as sess:
        print(just_bryond_primes.eval())

[ 3  4  6  8 12 14]


### 张量形状

In [6]:
with tf.Graph().as_default():
    #0维 scalar 标量
    scalar = tf.zeros([])
    #1维,vector 矢量
    vector = tf.zeros([3])
    #2x3矩阵
    matrix = tf.zeros([2,3])
    
    with tf.Session() as sess:
        print('scalar has shape',scalar.get_shape(),'and value:\n',scalar.eval())
        print('vector has shape',vector.get_shape(),'and value:\n',vector.eval())
        print('matrix has shape',matrix.get_shape(),'and value:\n',matrix.eval())

scalar has shape () and value:
 0.0
vector has shape (3,) and value:
 [0. 0. 0.]
matrix has shape (2, 3) and value:
 [[0. 0. 0.]
 [0. 0. 0.]]


### 广播加法

In [7]:
with tf.Graph().as_default():
    #包含六个元素的一维张量,vector
    primes = tf.constant([2,3,5,7,11,13],dtype=tf.int32)
    #标量
    ones = tf.constant(1,dtype=tf.int32)
    
    #加法
    just_bryond_primes = tf.add(primes,ones)
    
    with tf.Session() as sess:
        print(just_bryond_primes.eval())

[ 3  4  6  8 12 14]


## 矩阵乘法

In [8]:
with tf.Graph().as_default():
    #3x4矩阵
    x = tf.constant([[5,2,4,3],
                    [5,1,6,-2],
                    [-1,3,-1,-1]],dtype=tf.int32)
    #4x2矩阵
    y = tf.constant([[2,2],
                    [3,5],[4,5],[1,6]],dtype=tf.int32)
    #*
    matrix_multiply_result = tf.matmul(x,y)
    
    with tf.Session() as sess:
        print(matrix_multiply_result.eval())

[[35 58]
 [35 33]
 [ 2  2]]


## 张量变形

In [9]:
with tf.Graph().as_default():
    #8x2矩阵
    matrix = tf.constant([[1,2],
                         [3,4],[5,6],[7,8],[9,10],[11,12],[13,14],[15,16]],dtype=tf.int32)
    #将8x2矩阵变为2x8矩阵
    reshaped_2x8_matrix = tf.reshape(matrix,[2,8])
    #将8x2矩阵变为4x4矩阵
    reshaped_4x4_matrix = tf.reshape(matrix,[4,4])
    
    with tf.Session() as sess:
        print('Original matrix (8x2):')
        print(matrix.eval())
        print('Reshaped matrix (2x8)')
        print(reshaped_2x8_matrix.eval())
        print('reshaped_4x4_matrix:')
        print(reshaped_4x4_matrix.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped matrix (2x8)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
reshaped_4x4_matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### 改变维数

In [11]:
with tf.Graph().as_default():
    #8x2矩阵
    matrix = tf.constant([[1,2],
                         [3,4],[5,6],[7,8],[9,10],[11,12],[13,14],[15,16]],dtype=tf.int32)
    #将8x2 矩阵变为 2x2x4矩阵
    reshaped_2x2x4_tensor = tf.reshape(matrix,[2,2,4])
    #将8x2 矩阵变为 包含十六个元素的一维张量,即标量
    one_dimensional_vector = tf.reshape(matrix,[16])
    
    with tf.Session() as sess:
        print('Original matrix (8x2)')
        print(matrix.eval())
        print('Reshaped 3-D tensor (2x2x4):')
        print(reshaped_2x2x4_tensor.eval())
        print('1-D vector')
        print(one_dimensional_vector.eval())

Original matrix (8x2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped 3-D tensor (2x2x4):
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
1-D vector
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


### ex

In [13]:
with tf.Session().as_default():
    a = tf.constant([5, 3, 2, 7, 1, 4])
    b = tf.constant([4, 6, 3])
    
    reshaped_a = tf.reshape(a,[2,3])
    reshaped_b = tf.reshape(b,[3,1])
    mat = tf.matmul(reshaped_a,reshaped_b)
    with tf.Session() as sess:
        print(mat.eval())

[[44]
 [46]]


## 变量/初始化和赋值

### 变量

In [20]:
g = tf.Graph()
with g.as_default():
    #创建初始值为3的变量
    v = tf.Variable([3])
    #创建形状为[1],随机值为初始值得变量
    w = tf.Variable(tf.random_normal([1],mean=1.0,stddev=0.35))

### 初始化

In [21]:
with g.as_default():
    with tf.Session() as sess:
        initialzation = tf.global_variables_initializer() #初始化
        sess.run(initialzation)
        #分配值
        print(v.eval())
        print(w.eval())

[3]
[1.2016622]


### 改变变量的值

In [23]:
with g.as_default():
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer()) #每次会话都必须初始化变量
        print(v.eval()) #输出变量初始值
        
        #分配新值
        assignment = tf.assign(v,[7])
        print(v.eval()) #输出改变值
        
        sess.run(assignment) #执行分配新值操作
        print(v.eval()) #更新

[3]
[3]
[7]


### ex

In [26]:
with tf.Graph().as_default(),tf.Session() as sess:
    dice1 = tf.Variable(tf.random_uniform([10,1],minval=1,maxval=7,dtype=tf.int32)) #10x1矩阵,指定最大和最小值,指定类型为整型
    dice2 = tf.Variable(tf.random_uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
    sum_dice = tf.add(dice1,dice2)
    result_matrix = tf.concat(values=[dice1,dice2,sum_dice],axis=1) #指定在列维度上合并
    sess.run(tf.global_variables_initializer())
    print(result_matrix.eval())

[[ 1  6  7]
 [ 6  6 12]
 [ 2  1  3]
 [ 1  6  7]
 [ 6  4 10]
 [ 5  4  9]
 [ 2  1  3]
 [ 5  1  6]
 [ 6  1  7]
 [ 5  2  7]]
