## Layers

In [4]:
import torch
from torch.nn import Linear,ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable

In [5]:
myLayer = Linear(in_features=10,out_features=5,bias=True)
inp = Variable(torch.randn(1,10))
myLayer(inp)

tensor([[-0.9238, -1.0199,  0.9548,  0.0359,  0.1882]])

In [6]:
myLayer.weight

Parameter containing:
tensor([[ 0.1039, -0.1454,  0.2613,  0.2952,  0.0666, -0.2645,  0.1444,
         -0.2183, -0.2651, -0.1916],
        [-0.2693,  0.1959,  0.2584, -0.0658, -0.2860, -0.2217, -0.2052,
         -0.2320, -0.1236, -0.1300],
        [ 0.1503, -0.1667, -0.1051,  0.0512,  0.1928,  0.1826,  0.1514,
         -0.2630,  0.0451, -0.1088],
        [-0.2240, -0.0299, -0.2938, -0.2723,  0.3138, -0.3146,  0.0774,
          0.2559,  0.1027, -0.2414],
        [ 0.3009,  0.2400,  0.2399,  0.1255,  0.1299,  0.0019, -0.0289,
         -0.2965, -0.1346,  0.0993]])

In [7]:
myLayer.bias

Parameter containing:
tensor([-0.2406, -0.2273, -0.0817, -0.0602, -0.0060])

### 堆积

In [8]:
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[ 0.7320, -0.4947]])

## 激活函数

In [9]:
sample_data = Variable(torch.Tensor([[1,2,-1,-1]]))
myRelu = ReLU()
myRelu(sample_data)

tensor([[ 1.,  2.,  0.,  0.]])

### 更简写法

In [10]:
import torch.nn as nn 
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-1]]))
f = F.relu(sample_data)
f

tensor([[ 1.,  2.,  0.,  0.]])

## 我的第一个神经网络 with Pytorch

In [11]:
class MyFirstNetwork(nn.Module):
    def __init__(self,input_size,hiddle_size,output_size):
        super(MyFirstNetwork,self).__init__
        self.layer1 == nn.Linear(input_size,hiddle_size)
        self.layer2 == nn.Linear(hiddle_size,output_size)
    def __forward__(self,input):
        out = self.layer1(input)
        out = nn.ReLU(out)
        out = self.layer2(out)
        return out

### loss

In [12]:
loss = nn.MSELoss()
input = Variable(torch.randn(3,5),requires_grad=True)
target = Variable(torch.randn(3,5))
output = loss(input,target)
output.backward()

In [13]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3,5),requires_grad=True)
target = Variable(torch.LongTensor(3).random_(5))
output = loss(input,target)
output.backward()

### Optimizer

In [14]:
import torch.optim as optim

In [16]:
optimizer = optim.SGD(model.parameters(),lr=0.01)
for input,target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output,target)
    loss.backward()
    optimizer.step()

NameError: name 'model' is not defined

无 model, 仅为验证